# Generated by Django 2.0.3 on 2018-03-15 07:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ForumUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=30, unique=True)),
                ('photo', models.ImageField(blank=True, upload_to='users/%Y/%m/%d', verbose_name='头像')),
                ('signature', models.CharField(blank=True, max_length=30, verbose_name='个性签名')),
                ('total_topic', models.PositiveIntegerField(default=0, verbose_name='总帖子')),
                ('total_post', models.PositiveIntegerField(default=0, verbose_name='总回复')),
                ('total_agree', models.PositiveIntegerField(default=0, verbose_name='总赞数积分')),
            ],
            options={
                'permissions': (('read', '阅读'), ('reply', '回复'), ('post', '发帖'), ('delete', '删除'), ('control', '控制')),
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=4000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('slug', models.SlugField(editable=False, max_length=40, unique=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=256)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('slug', models.SlugField(editable=False, max_length=40, unique=True)),
                ('state', models.CharField(choices=[('hot', '热帖'), ('normal', ' 普通'), ('water', '刷屏'), ('attack', '攻击'), ('ad', '广告'), ('illegal', '违规')], max_length=10)),
                ('report', models.CharField(choices=[('water', '刷屏'), ('attack', '攻击'), ('ad', '广告'), ('illegal', '违规')], max_length=10)),
                ('agree', models.PositiveIntegerField(default=0)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='forums.Board')),
                ('starter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='forums.Topic'),
        ),
        migrations.AddField(
            model_name='post',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='forumuser',
            name='collection',
            field=models.ManyToManyField(related_name='collection_users', to='forums.Topic', verbose_name='收藏'),
        ),
        migrations.AddField(
            model_name='forumuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='forum_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
