# Generated by Django 2.0.3 on 2018-03-20 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0002_topic_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='content',
        ),
    ]
