# Generated by Django 2.0.3 on 2018-03-20 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0003_remove_topic_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='state',
            field=models.CharField(choices=[('hot', '热帖'), ('normal', ' 普通'), ('water', '刷屏'), ('attack', '攻击'), ('ad', '广告'), ('illegal', '违规')], default=('normal', '普通'), max_length=20),
        ),
    ]
