# Generated by Django 2.0.3 on 2018-03-20 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0004_auto_20180320_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumuser',
            name='collection',
            field=models.ManyToManyField(blank=True, related_name='collection_users', to='forums.Topic', verbose_name='收藏'),
        ),
    ]
