# Generated by Django 2.0.1 on 2018-02-04 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bid', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid_action',
            name='hander_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bid_actions', to='bid.Bid_hander'),
        ),
    ]
