# Generated by Django 2.0.2 on 2018-02-05 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bid', '0002_auto_20180204_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid_action',
            name='action_result',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
