# Generated by Django 2.0.2 on 2018-02-05 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bid', '0003_auto_20180205_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid_action',
            name='action_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='bid_auction',
            name='expired_date',
            field=models.DateField(),
        ),
    ]
