# Generated by Django 2.0.2 on 2018-02-05 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bid', '0004_auto_20180205_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid_auction',
            name='status',
            field=models.CharField(max_length=8),
        ),
    ]
