# Generated by Django 2.0.2 on 2018-02-06 02:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bid', '0005_auto_20180205_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid_action',
            name='auction_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auction_actions', to='bid.Bid_auction'),
        ),
        migrations.AlterField(
            model_name='bid_action',
            name='hander_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hander_actions', to='bid.Bid_hander'),
        ),
        migrations.AlterField(
            model_name='bid_hander',
            name='user_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_handers', to=settings.AUTH_USER_MODEL),
        ),
    ]
