# Generated by Django 2.0.2 on 2018-02-23 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bid', '0006_auto_20180206_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid_hander',
            name='hander_passwd',
            field=models.CharField(default='123456', max_length=32),
        ),
        migrations.AlterField(
            model_name='bid_hander',
            name='hander_name',
            field=models.CharField(default='a', max_length=32),
        ),
    ]
