# Generated by Django 2.0.3 on 2018-03-16 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bid', '0007_auto_20180223_0303'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bid_auction',
            table='bid_auction',
        ),
    ]
